apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}-service
  labels:
    app: ${PROJECT_NAME}-service
spec:
  type: ClusterIP
  ports:
    - port: ${PROJECT_PORT}
      targetPort: ${PROJECT_PORT}
      protocol: TCP
  selector:
    app: ${PROJECT_NAME}-service
